export enum CacheKey {
  CURRENT_USER = "current-user",
  LOGIN = "login",
  USERS = "users",
  USER = "user",
  EXCHANGE_RATE = "exchange-rate",
  POOLS = "pools",
  POOL = "pool",
  PROJECTS = "projects",
  PROJECT = "project",
  USER_PROJECTS = "user-projects",
  POOL_PROJECTS = "pool-projects",
  PROJECT_SUPPORTERS = "project-supporters",
  PROJECT_UPDATES = "project-updates",
  CHECKOUT_LINK = "checkout-link",
  CHECKOUT_MINT_LINK = "checkout-mint-link",
}
