export enum CacheKey {
  // query
  CURRENT_USER = 'current-user',
  LOGIN = 'login',
  USERS = 'users',
  USER = 'user',
  EXCHANGE_RATE = 'exchange-rate',
  POOLS = 'pools',
  POOL = 'pool',
  PROJECTS = 'projects',
  PROJECT = 'project',
  USER_PROJECTS = 'user-projects',
  POOL_PROJECTS = 'pool-projects',
  PROJECT_SUPPORTERS = 'project-supporters',
  PROJECT_BELIEVERS = 'project-believers',
  PROJECT_UPDATES = 'project-updates',
  CHECKOUT_LINK = 'checkout-link',
  CHECKOUT_MINT_LINK = 'checkout-mint-link',
  TOTAL_CONTRIBUTION = 'total-contribution',
  // mutation
  DOWNLOAD_PROJECT_SUPPORTERS = 'download-project-supporters',
  BELIEVE_PROJECT = 'believe-project',
  UDPATE_PROJECT_STATUS = 'update-project-status',
  DELETE_PROJECT = 'delete-project',
  CREATE_PROJECT = 'create-project',
  CREATE_POOL = 'create-pool',
}
